apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  runtime: nodejs18
  source:
    git:
      url: https://github.com/alesierraalta/MenuDigitalBack
      branch: main
  run:
    cmd: node dist/main.js
  build:
    cmd: npm install && npm run build
  env:
    - name: NODE_ENV
      value: production
  inbound:
    - name: CategoriasService
      port: 3001
      type: REST
      networkVisibility: Public
      context: /api/categorias
      schemaFilePath: ./swagger/categorias.yaml
    - name: CategoriaDetailService
      port: 3001
      type: REST
      networkVisibility: Public
      context: /api/categorias/:id
      schemaFilePath: ./swagger/categorias.yaml
    - name: CreateCategoriaService
      port: 3001
      type: REST
      networkVisibility: Public
      context: /api/categorias
      schemaFilePath: ./swagger/categorias.yaml
    - name: UpdateCategoriaService
      port: 3001
      type: REST
      networkVisibility: Public
      context: /api/categorias/:id
      schemaFilePath: ./swagger/categorias.yaml
    - name: DeleteCategoriaService
      port: 3001
      type: REST
      networkVisibility: Public
      context: /api/categorias/:id
      schemaFilePath: ./swagger/categorias.yaml
    - name: ComidasService
      port: 3001
      type: REST
      networkVisibility: Public
      context: /api/comidas
      schemaFilePath: ./swagger/comidas.yaml
    - name: ComidaDetailService
      port: 3001
      type: REST
      networkVisibility: Public
      context: /api/comidas/:id
      schemaFilePath: ./swagger/comidas.yaml
    - name: ComidasByCategoriaService
      port: 3001
      type: REST
      networkVisibility: Public
      context: /api/comidas/categoria/:id_categoria
      schemaFilePath: ./swagger/comidas.yaml
    - name: ComidasSearchService
      port: 3001
      type: REST
      networkVisibility: Public
      context: /api/comidas/buscar
      schemaFilePath: ./swagger/comidas.yaml
    - name: CreateComidaService
      port: 3001
      type: REST
      networkVisibility: Public
      context: /api/comidas
      schemaFilePath: ./swagger/comidas.yaml
    - name: UpdateComidaService
      port: 3001
      type: REST
      networkVisibility: Public
      context: /api/comidas/:id
      schemaFilePath: ./swagger/comidas.yaml
    - name: DeleteComidaService
      port: 3001
      type: REST
      networkVisibility: Public
      context: /api/comidas/:id
      schemaFilePath: ./swagger/comidas.yaml
